### ISSUE TITLE
Errors with make command

### ISSUE THREAD

**Issue by Digipup1** [blitzcode/hue-dash#1]
I replaced my ip of my hub in the id section in the main.c file then put my mac addresses in for my buttons then tried to compile but got the following errors `cc -std=c99 -g -O -Wall -Wextra -Wno-unused-parameter   -c -o main.o main.c
main.c: In function ‘main’:
main.c:146:2: error: ‘jj’ undeclared (first use in this function)
  jj=-098           eth_hdr->h_source[0], eth_hdr->h_source[1], eth_hdr->h_source[2],
  ^
main.c:146:2: note: each undeclared identifier is reported only once for each function it appears in
main.c:146:6: error: invalid digit "9" in octal constant
  jj=-098           eth_hdr->h_source[0], eth_hdr->h_source[1], eth_hdr->h_source[2],
      ^
main.c:146:20: error: expected ‘)’ before ‘eth_hdr’
  jj=-098           eth_hdr->h_source[0], eth_hdr->h_source[1], eth_hdr->h_source[2],
                    ^
<builtin>: recipe for target 'main.o' failed
make: *** [main.o] Error 1
`

**Comment by blitzcode** [comment]
Does it build when you reset your working directory and use the unmodified version?

**Comment by Digipup1** [comment]
When I build with the unmodified version it returns `cc -std=c99 -g -O -Wall -Wextra -Wno-unused-parameter   -c -o main.o main.c
cc -o out -std=c99 -g -O -Wall -Wextra -Wno-unused-parameter  main.o `

**Comment by blitzcode** [comment]
Looks like you just made a typo when you modified the source then? The error messages you posted don't seem to correspond to anything that's actually in the original code.

**Comment by Digipup1** [comment]
Thanks.
